### ISSUE TITLE
Update screenshots on Steam's workshop w/ the last update

### ISSUE THREAD

**Issue by Kileahh** [ScribioTeam/OWB_French_Translation#13]
If some time is available, maybe screenshots on the steam's workshop can be updated to match with the last  mod translation version ?

**Comment by NicolasGrosjean** [comment]
@Kileahh Normally I have chosen to capture some part of the games which are already fully translated.
Do you have an idea of the screenshots which can be not up-to-date ?

**Comment by Kileahh** [comment]
![image](https://user-images.githubusercontent.com/13626201/44956471-3e312a80-aec5-11e8-8c04-689f81bb8910.png)

Some modifications has been with #5 about the harmonization. (eg : "Rame à vapeur" became "Bateau à roues à aubes" )

**Comment by NicolasGrosjean** [comment]
![9](https://user-images.githubusercontent.com/13560473/44956652-b6005480-aec7-11e8-85f8-300f29bfcd92.jpg)
