### ISSUE TITLE
Same texts, but different keys

### ISSUE THREAD

**Issue by Kileahh** [ScribioTeam/OWB_French_Translation#14]
Good one ?

https://github.com/ScribioTeam/OWB_French_Translation/blob/14d5fa9f4bcdd5249578a5dbb0db67e3452b7e20/OWB/localisation/immersive_locations_l_french.yml#L27-L28

Wrong one ?

https://github.com/ScribioTeam/OWB_French_Translation/blob/14d5fa9f4bcdd5249578a5dbb0db67e3452b7e20/OWB/localisation/immersive_locations_l_french.yml#L42-L43

The same problem exists in the l_english file.

**Comment by NicolasGrosjean** [comment]
@Kileahh If the problem exists in English, I suggest to fix it when they fix it in order to continue to do easy updates.
