### ISSUE TITLE
Ajout du lien Discord

### ISSUE THREAD

**Issue by Warkild** [ScribioTeam/OWB_French_Translation#17]
Il faut ajouter le lien Discord de Scribio dans le menu et dans l'event de Scribio

**Comment by NicolasGrosjean** [comment]
![image](https://user-images.githubusercontent.com/13560473/45712542-e49b5200-bb8c-11e8-9703-9c5f710dfcef.png)

![image](https://user-images.githubusercontent.com/13560473/45712573-fd0b6c80-bb8c-11e8-9407-add994f703c0.png)

**Comment by NicolasGrosjean** [comment]
![image](https://user-images.githubusercontent.com/13560473/45712869-b9fdc900-bb8d-11e8-9cd1-e69e11d4e64c.png)
